version: '3.2'

services:
  apache_php5:
    build: './php/'
    depends_on:
      - mongo
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./code/public_html/:/var/www/html/
      - ./code/application/:/var/www/application/
      - ./code/lib/:/var/www/lib/
    environment:
      WAIT_HOSTS: mongo:27017
  # mysql:
  #   image: mysql:5.6.40
  #   networks:
  #     - backend
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  mongo:
    image: mongo
    networks:
      - backend
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles
networks:
  # frontend:
  backend:
